### ISSUE TITLE
Changes of path are not persisted between phases

### ISSUE THREAD

**Issue by julienvey** [bazooka-ci/bazooka#251]
For some projects, commands need to be run not at the root of the project, for instance, in a `source` directory.

A way to achieve this is to add the `cd` command in the `before_install` phase

But this change of path is not persisted

```yaml
before_install:
  - cd source
  - pwd #/bazooka/source

install:
  - pwd #/bazooka
```
