### ISSUE TITLE
Manage Exclude and Include in build matrix 

### ISSUE THREAD

**Issue by julienvey** [bazooka-ci/bazooka#27]
Need #26 first

see http://docs.travis-ci.com/user/build-configuration/#The-Build-Matrix

**Comment by jawher** [comment]
This too is a tough one: it would require some extensive rework of the tricky *(fragile ?)* interplay we have between parser and parserlang regarding the permutation generation.

How this works now:

* parserlang uses the top level configuration key (jdk, go, python, etc.) to generate the first set of permutations
* parser then multiplies these permutations by the env vars permutations to generate all the possible variants, excluding the ones matching the exclusion matric

To correctly handle matrix includes, and since with includes the user can decide to not specify a top level list of versions of the language but instead only define them in the include list, like for example:

```yaml
language: go
matrix:
  include:
    - go: 1.4
      env: GOARCH=x86
    - go: 1.3
      env: GOARCH=x86_64
```

Such cases are not compatible with the current approach, as the parserlang will need to peek into the includes to be able to set the `from_image` key.

**Comment by julienvey** [comment]
It would also be great to handle permutations this way

```yaml
env:
  matrix:
    - VAGRANT_VERSION=v1.4.3 BUNDLER_VERSION=1.6.6
    - VAGRANT_VERSION=v1.5.4 BUNDLER_VERSION=1.5.2
    - VAGRANT_VERSION=v1.6.5 BUNDLER_VERSION=1.6.6
    - VAGRANT_VERSION=v1.7.2 BUNDLER_VERSION=1.6.6
```
